# Generated by Django 5.2.7 on 2025-12-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='store.category'),
        ),
    ]
