# Generated by Django 5.2.7 on 2025-12-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_vendor_product_discount_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(blank=True, help_text='Usage instructions.'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Enter ingredients here. Press Enter for new lines.'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_info',
            field=models.TextField(blank=True, default='Standard delivery charges apply. Delivery within 3-5 working days.'),
        ),
    ]
