# Generated by Django 5.2.7 on 2025-11-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cod', max_length=20),
        ),
    ]
