# Generated by Django 5.2.7 on 2025-11-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_items', '0002_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
