# Generated by Django 5.2.7 on 2025-11-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_items', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
